export default {
    SUCCESS_LOGIN: "SUCCESS_LOGIN",
    FAILURE_LOGIN: "FAILURE_LOGIN",
    START_FETCHING: "START_FETCHING",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    ADD_ERROR: "ADD_ERROR",
    SUCCESS_LOGOUT: "SUCCESS_LOGOUT",
    FAILURE_LOGOUT: "FAILURE_LOGOUT"
}
